# Generated by Django 6.0.1 on 2026-09-08 13:48

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_announcement_notification_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notifications/attachments/', validators=[main.validators.validate_public_file]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notifications/attachments/', validators=[main.validators.validate_public_file]),
        ),
    ]
