# Generated by Django 6.0.1 on 2026-09-08 14:03

import main.storage_backends
import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_announcement_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=main.storage_backends.PublicMediaStorage(), upload_to='notifications/attachments/', validators=[main.validators.validate_public_file]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=main.storage_backends.PublicMediaStorage(), upload_to='notifications/attachments/', validators=[main.validators.validate_public_file]),
        ),
    ]
