# Generated by Django 6.0.1 on 2026-09-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_announcement_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SYSTEM_ALERT', 'System Alert'), ('HOSPITAL_ANNOUNCEMENT', 'Hospital Announcement'), ('APPOINTMENT_UPDATE', 'Appointment Update'), ('MEDICATION_REMINDER', 'Medication Reminder'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
