# Generated by Django 6.0.1 on 2026-05-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctor", "0019_remove_doctorprofile_address"),
        ("patient", "0007_patientprofile_allergies_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdviceChatThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thread_code", models.CharField(max_length=20, unique=True)),
                ("status", models.CharField(choices=[("OPEN", "Open"), ("CLOSED", "Closed")], default="OPEN", max_length=20)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_threads",
                        to="doctor.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_threads",
                        to="patient.patientprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["doctor", "status"], name="chat_thread_doctor_status_idx"),
                    models.Index(fields=["patient", "status"], name="chat_thread_patient_status_idx"),
                    models.Index(fields=["last_message_at"], name="chat_thread_last_msg_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=["doctor", "patient"], name="unique_advice_chat_thread_participants"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdviceChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_role",
                    models.CharField(choices=[("DOCTOR", "Doctor"), ("PATIENT", "Patient")], max_length=20),
                ),
                ("message_text", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.advicechatthread",
                    ),
                ),
            ],
            options={
                "ordering": ["sent_at", "id"],
                "indexes": [
                    models.Index(fields=["thread", "sent_at"], name="chat_msg_thread_sent_idx"),
                    models.Index(fields=["sender_user", "sent_at"], name="chat_msg_sender_sent_idx"),
                    models.Index(fields=["is_read", "sent_at"], name="chat_msg_read_sent_idx"),
                ],
            },
        ),
    ]
