# Generated by Django 6.0.1 on 2026-05-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='advicechatmessage',
            new_name='chat_advice_thread__669a7c_idx',
            old_name='chat_msg_thread_sent_idx',
        ),
        migrations.RenameIndex(
            model_name='advicechatmessage',
            new_name='chat_advice_sender__3c257a_idx',
            old_name='chat_msg_sender_sent_idx',
        ),
        migrations.RenameIndex(
            model_name='advicechatmessage',
            new_name='chat_advice_is_read_523505_idx',
            old_name='chat_msg_read_sent_idx',
        ),
        migrations.RenameIndex(
            model_name='advicechatthread',
            new_name='chat_advice_doctor__0c0794_idx',
            old_name='chat_thread_doctor_status_idx',
        ),
        migrations.RenameIndex(
            model_name='advicechatthread',
            new_name='chat_advice_patient_99412f_idx',
            old_name='chat_thread_patient_status_idx',
        ),
        migrations.RenameIndex(
            model_name='advicechatthread',
            new_name='chat_advice_last_me_38ddd8_idx',
            old_name='chat_thread_last_msg_idx',
        ),
    ]
