# Generated by Django 5.1.15 on 2026-06-21 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chat",
            "0002_rename_chat_msg_thread_sent_idx_chat_advice_thread__669a7c_idx_and_more",
        ),
        ("doctor", "0023_remove_hospitaladmin_hospital_and_more"),
        ("hospital", "0005_alter_activitylog_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advicechatmessage",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="chat_attachments/"
            ),
        ),
        migrations.AddField(
            model_name="advicechatthread",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advicechatthread",
            name="price_paid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name="DoctorChatSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration_minutes", models.IntegerField(default=1440)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_slots",
                        to="doctor.doctorprofile",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_slots",
                        to="hospital.hospital",
                    ),
                ),
            ],
        ),
    ]
