# Generated by Django 5.1.15 on 2026-08-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_advicechatmessage_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advicechatthread',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
