# Generated by Django 6.0.1 on 2026-06-25 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_advicechatmessage_attachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatCryptoKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField(help_text='RSA Public Key in SPKI/JWK format')),
                ('private_key', models.TextField(help_text='RSA Private Key in PKCS8/JWK format (encrypted or plaintext depending on server-trust model)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_crypto_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
