# Generated by Django 6.0.1 on 2026-09-08 13:48

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_advicechatthread_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advicechatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/', validators=[main.validators.validate_private_file]),
        ),
    ]
