# Generated by Django 6.0.1 on 2026-09-08 14:03

import main.storage_backends
import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_advicechatmessage_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advicechatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=main.storage_backends.PrivateMediaStorage(), upload_to='chat_attachments/', validators=[main.validators.validate_private_file]),
        ),
    ]
