# Generated by Django 6.0.1 on 2026-07-04 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0023_remove_hospitaladmin_hospital_and_more'),
        ('hospital', '0005_alter_activitylog_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='slottemplate',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_app_slot_templates', to='doctor.doctorprofile'),
        ),
        migrations.CreateModel(
            name='DoctorSlotTemplateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_template_assignments', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_assignments', to='doctor.doctorprofile')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_template_assignments', to='hospital.hospital')),
                ('slot_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hospital.slottemplate')),
            ],
            options={
                'indexes': [models.Index(fields=['doctor', 'hospital'], name='hospital_do_doctor__9cc7ce_idx')],
            },
        ),
    ]
