# Generated by Django 5.1.15 on 2026-07-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0006_alter_slottemplate_doctor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="slottemplate",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
