DOCTOR_SPECIALIZATIONS = [
    "Allergy and Immunology",
    "Anesthesiology",
    "Cardiology",
    "Cardiothoracic Surgery",
    "Clinical Genetics",
    "Clinical Oncology",
    "Critical Care Medicine",
    "Dermatology",
    "Emergency Medicine",
    "Endocrinology",
    "Family Medicine",
    "Forensic Medicine",
    "Gastroenterology",
    "General Practitioner",
    "General Surgery",
    "Geriatric Medicine",
    "Gynecology",
    "Hematology",
    "Hepatology",
    "Infectious Diseases",
    "Internal Medicine",
    "Interventional Radiology",
    "Nephrology",
    "Neurology",
    "Neurosurgery",
    "Nuclear Medicine",
    "Obstetrics",
    "Occupational Medicine",
    "Oncology",
    "Ophthalmology",
    "Oral and Maxillofacial Surgery",
    "Orthopedic Surgery",
    "Otolaryngology (ENT)",
    "Palliative Medicine",
    "Pathology",
    "Pediatric Cardiology",
    "Pediatrics",
    "Physical Medicine and Rehabilitation",
    "Plastic and Reconstructive Surgery",
    "Psychiatry",
    "Pulmonology",
    "Radiology",
    "Rheumatology",
    "Sports Medicine",
    "Urology",
    "Vascular Surgery",
    "Other",
]
