# Generated by Django 5.1.15 on 2026-02-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0002_patientprofile_delete_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofile",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
