# Generated by Django 6.0.1 on 2026-02-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0003_alter_patientprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
