# Generated by Django 6.0.1 on 2026-05-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0004_alter_patientprofile_id"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE patient_patientprofile ADD COLUMN IF NOT EXISTS blood_type varchar(5) NOT NULL DEFAULT '';",
                    reverse_sql="ALTER TABLE patient_patientprofile DROP COLUMN IF EXISTS blood_type;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE patient_patientprofile ADD COLUMN IF NOT EXISTS city varchar(100) NOT NULL DEFAULT '';",
                    reverse_sql="ALTER TABLE patient_patientprofile DROP COLUMN IF EXISTS city;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE patient_patientprofile ADD COLUMN IF NOT EXISTS country varchar(100) NOT NULL DEFAULT '';",
                    reverse_sql="ALTER TABLE patient_patientprofile DROP COLUMN IF EXISTS country;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE patient_patientprofile ADD COLUMN IF NOT EXISTS emergency_contact_name varchar(255) NOT NULL DEFAULT '';",
                    reverse_sql="ALTER TABLE patient_patientprofile DROP COLUMN IF EXISTS emergency_contact_name;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE patient_patientprofile ADD COLUMN IF NOT EXISTS emergency_contact_phone varchar(20) NOT NULL DEFAULT '';",
                    reverse_sql="ALTER TABLE patient_patientprofile DROP COLUMN IF EXISTS emergency_contact_phone;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE patient_patientprofile ADD COLUMN IF NOT EXISTS emergency_contact_relation varchar(100) NOT NULL DEFAULT '';",
                    reverse_sql="ALTER TABLE patient_patientprofile DROP COLUMN IF EXISTS emergency_contact_relation;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE patient_patientprofile ADD COLUMN IF NOT EXISTS insurance_policy_number varchar(100) NOT NULL DEFAULT '';",
                    reverse_sql="ALTER TABLE patient_patientprofile DROP COLUMN IF EXISTS insurance_policy_number;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE patient_patientprofile ADD COLUMN IF NOT EXISTS insurance_provider varchar(255) NOT NULL DEFAULT '';",
                    reverse_sql="ALTER TABLE patient_patientprofile DROP COLUMN IF EXISTS insurance_provider;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE patient_patientprofile ADD COLUMN IF NOT EXISTS medications text NOT NULL DEFAULT '';",
                    reverse_sql="ALTER TABLE patient_patientprofile DROP COLUMN IF EXISTS medications;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE patient_patientprofile ADD COLUMN IF NOT EXISTS postal_code varchar(20) NOT NULL DEFAULT '';",
                    reverse_sql="ALTER TABLE patient_patientprofile DROP COLUMN IF EXISTS postal_code;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="patientprofile",
                    name="blood_type",
                    field=models.CharField(blank=True, default="", max_length=5),
                ),
                migrations.AddField(
                    model_name="patientprofile",
                    name="city",
                    field=models.CharField(blank=True, default="", max_length=100),
                ),
                migrations.AddField(
                    model_name="patientprofile",
                    name="country",
                    field=models.CharField(blank=True, default="", max_length=100),
                ),
                migrations.AddField(
                    model_name="patientprofile",
                    name="emergency_contact_name",
                    field=models.CharField(blank=True, default="", max_length=255),
                ),
                migrations.AddField(
                    model_name="patientprofile",
                    name="emergency_contact_phone",
                    field=models.CharField(blank=True, default="", max_length=20),
                ),
                migrations.AddField(
                    model_name="patientprofile",
                    name="emergency_contact_relation",
                    field=models.CharField(blank=True, default="", max_length=100),
                ),
                migrations.AddField(
                    model_name="patientprofile",
                    name="insurance_policy_number",
                    field=models.CharField(blank=True, default="", max_length=100),
                ),
                migrations.AddField(
                    model_name="patientprofile",
                    name="insurance_provider",
                    field=models.CharField(blank=True, default="", max_length=255),
                ),
                migrations.AddField(
                    model_name="patientprofile",
                    name="medications",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="patientprofile",
                    name="postal_code",
                    field=models.CharField(blank=True, default="", max_length=20),
                ),
            ],
        ),
    ]
