# Generated by Django 6.0.1 on 2026-05-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_patientprofile_profile_picture'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE patient_patientprofile ADD COLUMN IF NOT EXISTS allergies text NOT NULL DEFAULT '';",
                    reverse_sql="ALTER TABLE patient_patientprofile DROP COLUMN IF EXISTS allergies;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='patientprofile',
                    name='allergies',
                    field=models.TextField(blank=True, default=''),
                ),
                migrations.AlterField(
                    model_name='patientprofile',
                    name='blood_type',
                    field=models.CharField(blank=True, default='', max_length=10),
                ),
            ],
        ),
    ]
