# Generated by Django 5.1.15 on 2026-06-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0010_patientprofile_emergency_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofile",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
