# Generated by Django 5.1.15 on 2026-06-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0011_alter_patientprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
