# Generated by Django 6.0.1 on 2026-08-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0016_medication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientmedication",
            name="frequency",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
