# Generated by Django 6.0.1 on 2026-08-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_alter_patientmedication_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='insurance_policy_number',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='insurance_provider',
        ),
    ]
