# Generated by Django 6.0.1 on 2026-08-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_remove_patientprofile_insurance_policy_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedication',
            name='frequency',
            field=models.CharField(max_length=255),
        ),
    ]
