# Generated by Django 6.0.1 on 2026-09-08 13:48

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0021_medicationreminder_medicationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='medical_documents',
            field=models.FileField(blank=True, null=True, upload_to='patient_documents/', validators=[main.validators.validate_private_file]),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='medical_reports',
            field=models.FileField(blank=True, null=True, upload_to='patient_reports/', validators=[main.validators.validate_private_file]),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='patient_profiles/', validators=[main.validators.validate_public_file]),
        ),
    ]
