# Generated by Django 6.0.1 on 2026-09-06 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0021_medicationreminder_medicationlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicationlog",
            name="dosage",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="medicationlog",
            name="medicine_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="medicationlog",
            name="reminder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="patient.medicationreminder",
            ),
        ),
    ]
