# Generated by Django 6.0.1 on 2026-09-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0022_medicationlog_dosage_medicationlog_medicine_name_and_more'),
        ('patient', '0023_alter_patientprofile_medical_documents_and_more'),
    ]

    operations = [
    ]
