# Generated by Django 6.0.1 on 2026-09-12 15:26

import django.db.models.deletion
import main.storage_backends
import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0024_merge_20260912_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='medical_documents',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='medical_reports',
        ),
        migrations.CreateModel(
            name='PatientMedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=main.storage_backends.PrivateMediaStorage(), upload_to='patient_documents/', validators=[main.validators.validate_private_file])),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to='patient.patientprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
