# Generated by Django 6.0.1 on 2026-09-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0025_remove_patientprofile_medical_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationlog',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
