# Generated by Django 6.0.1 on 2026-09-22 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0024_repair_patient_profile_file_columns"),
        ("patient", "0026_medicationlog_notification_sent"),
    ]

    operations = []
