# Generated by Django 6.0.1 on 2026-01-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
