# Generated by Django 6.0.1 on 2026-01-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0003_doctorprofile_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="full_name",
            field=models.CharField(default="Doctor", max_length=255),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="nic_number",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="preferred_name",
            field=models.CharField(default="Dr.", max_length=100),
        ),
    ]
