# Generated by Django 6.0.1 on 2026-03-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0004_doctorprofile_full_name_doctorprofile_nic_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="availability",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="experience_years",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="hospitals",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="languages_spoken",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="location",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="doctor_profiles/"
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="qualifications",
            field=models.TextField(default=""),
        ),
    ]
