# Generated by Django 6.0.1 on 2026-03-07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctorprofile_availability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentAvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_of_week', models.CharField(blank=True, default='', max_length=12)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_slots', to='doctor.doctorprofile')),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(fields=('doctor', 'date', 'start_time', 'end_time'), name='unique_doctor_appointment_slot'),
                ],
            },
        ),
        migrations.CreateModel(
            name='DoctorAppointmentAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=12)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_availabilities', to='doctor.doctorprofile')),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(fields=('doctor', 'day_of_week', 'start_time', 'end_time'), name='unique_doctor_appointment_availability_window'),
                ],
            },
        ),
        migrations.CreateModel(
            name='DoctorOnlineAdviceAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=12)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_advice_availabilities', to='doctor.doctorprofile')),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(fields=('doctor', 'day_of_week', 'start_time', 'end_time'), name='unique_doctor_online_advice_availability_window'),
                ],
            },
        ),
    ]
