# Generated by Django 6.0.1 on 2026-03-17 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0006_appointment_slots_and_availability_models"),
        ("patient", "0004_alter_patientprofile_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="doctor.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="patient.patientprofile",
                    ),
                ),
                (
                    "slot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointment",
                        to="doctor.appointmentavailableslot",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["doctor", "slot"], name="doctor_appo_doctor__0e4290_idx"
                    ),
                    models.Index(
                        fields=["patient", "slot"],
                        name="doctor_appo_patient_d63c7f_idx",
                    ),
                    models.Index(
                        fields=["requested_at"], name="doctor_appo_request_8dc73a_idx"
                    ),
                ],
            },
        ),
    ]
