# Generated by Django 6.0.1 on 2026-04-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0007_appointment"),
        ("patient", "0004_alter_patientprofile_id"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="appointment",
            name="doctor_appo_doctor__0e4290_idx",
        ),
        migrations.RemoveIndex(
            model_name="appointment",
            name="doctor_appo_patient_d63c7f_idx",
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor", "status"], name="doctor_appo_doctor__cdfbb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "status"], name="doctor_appo_patient_d533eb_idx"
            ),
        ),
    ]
