# Generated by Django 6.0.1 on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0008_remove_appointment_doctor_appo_doctor__0e4290_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="appointment_fee",
            field=models.DecimalField(decimal_places=2, default=2000000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="chat_fee",
            field=models.DecimalField(decimal_places=2, default=1000000.0, max_digits=10),
        ),
    ]
