# Generated by ChatGPT on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0010_alter_appointment_slot_to_foreignkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentavailableslot",
            name="hospital",
            field=models.CharField(default="", max_length=255),
        ),
    ]
