# Generated by Django 6.0.1 on 2026-04-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0011_appointmentavailableslot_hospital"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentavailableslot",
            name="booked_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="appointmentavailableslot",
            name="remaining_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
