# Generated by Django 6.0.1 on 2026-04-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0012_appointmentavailableslot_booked_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="appointment_fee",
            field=models.DecimalField(decimal_places=2, default=3500.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="chat_fee",
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
    ]
