# Generated by Django 6.0.1 on 2026-05-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0013_alter_doctorprofile_appointment_fee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="experience_years",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="languages_spoken",
            field=models.CharField(default="English", max_length=255),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="location",
            field=models.CharField(default="Colombo, Sri Lanka", max_length=255),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="qualifications",
            field=models.TextField(default="MBBS, MD"),
        ),
    ]
