# Generated by Django 6.0.1 on 2026-05-13 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0015_hospital_appointment_cancellation_reason_and_more"),
        ("hospital", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="appointmentavailableslot",
            name="unique_doctor_appointment_slot",
        ),
        migrations.AddField(
            model_name="appointmentavailableslot",
            name="date_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointmentavailableslot",
            name="date_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="hospital.hospital",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentavailableslot",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_slots",
                to="hospital.hospital",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentavailableslot",
            name="slot_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_slots",
                to="hospital.slottemplate",
            ),
        ),
        migrations.AlterField(
            model_name="doctorhospitalverification",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hospital_verifications_old",
                to="doctor.doctorprofile",
            ),
        ),
        migrations.AlterField(
            model_name="doctorhospitalverification",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_verifications_old",
                to="doctor.hospital",
            ),
        ),
        migrations.AlterField(
            model_name="doctorhospitalverification",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verifications_done_old",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="hospitaladmin",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admins_old",
                to="doctor.hospital",
            ),
        ),
        migrations.AlterField(
            model_name="hospitaladmin",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hospital_admin_roles_old",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="slottemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_slot_templates_old",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="slottemplate",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slot_templates_old",
                to="doctor.doctorprofile",
            ),
        ),
        migrations.AlterField(
            model_name="slottemplate",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slot_templates_old",
                to="doctor.hospital",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmentavailableslot",
            constraint=models.UniqueConstraint(
                fields=("doctor", "date_start", "date_end"),
                name="unique_doctor_appointment_slot",
            ),
        ),
    ]
