# Generated by Django 5.1.15 on 2026-06-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0022_remove_doctorprofile_hospitals"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="hospitaladmin",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="hospitaladmin",
            name="hospital",
        ),
        migrations.RemoveField(
            model_name="slottemplate",
            name="hospital",
        ),
        migrations.RemoveField(
            model_name="hospitaladmin",
            name="user",
        ),
        migrations.RemoveField(
            model_name="slottemplate",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="slottemplate",
            name="doctor",
        ),
        migrations.DeleteModel(
            name="DoctorHospitalVerification",
        ),
        migrations.DeleteModel(
            name="Hospital",
        ),
        migrations.DeleteModel(
            name="HospitalAdmin",
        ),
        migrations.DeleteModel(
            name="SlotTemplate",
        ),
    ]
