# Generated by Django 6.0.1 on 2026-07-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0023_remove_hospitaladmin_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='inperson_doctor_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='inperson_hospital_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='online_doctor_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='online_hospital_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
