# Generated by Django 6.0.1 on 2026-09-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0027_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('CANCELLATION_REQUESTED', 'Cancellation Requested'), ('EXPIRED', 'Expired')], default='PENDING', max_length=30),
        ),
    ]
