# Generated by Django 6.0.1 on 2026-09-08 13:48

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0028_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_profiles/', validators=[main.validators.validate_public_file]),
        ),
    ]
