# Generated by Django 6.0.1 on 2026-09-08 14:03

import main.storage_backends
import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0029_alter_doctorprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=main.storage_backends.PublicMediaStorage(), upload_to='doctor_profiles/', validators=[main.validators.validate_public_file]),
        ),
    ]
