# Generated by Django 6.0.1 on 2026-01-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userotp"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("otp_code", models.CharField(max_length=6)),
                ("password", models.CharField(max_length=128)),
                ("role", models.CharField(max_length=50)),
                ("profile_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name="UserOTP",
        ),
    ]
