# Generated by Django 6.0.1 on 2026-03-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_useractivitylog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="useractivitylog",
            new_name="users_usera_created_281045_idx",
            old_name="users_usera_created_95a587_idx",
        ),
        migrations.RenameIndex(
            model_name="useractivitylog",
            new_name="users_usera_action__3c9654_idx",
            old_name="users_usera_action__bb7d57_idx",
        ),
        migrations.RenameIndex(
            model_name="useractivitylog",
            new_name="users_usera_actor_u_3e6b96_idx",
            old_name="users_usera_actor_u_472ff6_idx",
        ),
        migrations.RenameIndex(
            model_name="useractivitylog",
            new_name="users_usera_entity__4c04dd_idx",
            old_name="users_usera_entity__d1e933_idx",
        ),
    ]
