# Generated by Django 6.0.1 on 2026-04-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0005_rename_users_usera_created_95a587_idx_users_usera_created_281045_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pendinguser",
            name="otp_code_hash",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
