# Generated by Django 6.0.1 on 2026-04-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_pendinguser_otp_code_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendinguser",
            name="otp_failed_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pendinguser",
            name="otp_last_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pendinguser",
            name="otp_locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
