# Generated by Django 6.0.1 on 2026-05-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_pendinguser_otp_failed_attempts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("PATIENT", "Patient"),
                    ("DOCTOR", "Doctor"),
                    ("HOSPITAL_ADMIN", "Hospital Admin"),
                ],
                default="PATIENT",
                max_length=50,
            ),
        ),
    ]
