# Generated by Django 5.1.15 on 2026-06-26 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_customuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "otp_code_hash",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("otp_failed_attempts", models.PositiveSmallIntegerField(default=0)),
                ("otp_locked_until", models.DateTimeField(blank=True, null=True)),
                ("otp_last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_auth",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
