# Generated by Django 5.1.15 on 2026-07-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_userotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="userotp",
            name="last_otp_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
