# Generated by Django 5.1.15 on 2026-07-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_userotp_last_otp_verified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="dnd_enabled",
            field=models.BooleanField(
                default=False, help_text="Do Not Disturb mode for notifications"
            ),
        ),
    ]
